# This is the main docker stack for our provided tools
services:
  
  # This is the main postgresql server to be provided to teams
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    ports: # Expose for now but move to behind proxy
      - "5432:5432"
    networks:
      - proxy_net
      - monitoring_net
  
  # The reverse proxy that will act as the gateway for all services
  nginx_proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "81:81" # Admin Web Page
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - proxy_net
  
  # An uptime monitor that can track the status of applications and send notifications
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime_data:/app/data
    networks:
      - proxy_net
      # - monitoring_net
    ports:
      - "3001:3001"

volumes:
  postgres_main_data:
  nginx_data:
  nginx_letsencrypt:
  uptime_data:

networks:
  proxy_net: # The main network for proxied services
  monitoring_net: