services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro
    networks:
      # - monitoring
      - proxy_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --web.listen-address=:3002
    volumes:
      - /podman/monitoring/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    networks:
      # - monitoring
      - proxy_net

    # Internal Port: 3002

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - TZ=${TZ}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      # - proxy
      # - monitoring
      - proxy_net

    # Internal Port: 3000

volumes:
  prometheus_data:

  grafana_data:

networks:
  proxy:
  monitoring:
  proxy_net:
    name: main-stack_proxy_net
    external: true