services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /run/podman/podman.sock:/var/run/docker.sock:Z
    restart: always
    privileged: true
    networks:
      - proxy_net

volumes:
  portainer_data:
    external: true

networks:
  proxy_net: # The main network for proxied services
    name: main-stack_proxy_net
    external: true