# Run within portainer and set env variables with portainer

services:
  wiki_db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  wiki:
    image: requarks/wiki:2
    depends_on:
      - wiki_db
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wiki_db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=wiki
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  postgres_data: